r"""
Bootstrap a hint review queue for QLoRA training. The output is a queue for human review, not a
finished training set.

Approach (Issue 246, hybrid): candidate hints are generated by the live gate and `generate_hint()`
pipeline over the filtered candidate pool, but every candidate must go through a full human review
(review_hint_queue.py or confirm_hint_prescreen.py) before it can be a training target. The
reviewed text is what trains, never the raw bootstrap output. This script only builds the queue:
it trains nothing and does not write to `psle.db`.

Candidate pool: Issue 246's structural exclusion chain, re-run fresh, plus two filters added after
the integrity check:
    0. all rows
    1. exclude superseded_by IS NOT NULL          (dedup losers, Issues 231, 290)
    2. exclude extraction_flag ~ non_question_boilerplate
    3. require worked_solution_text               (the form-transfer signal for QLoRA, Issue 246)
    4. require answer_value                       [new: 1,827 rows had no answer]
    5. exclude extraction_flag ~ answer_key_verification_pending OR no_matching_answer_key_row
                                                  [new: quarantine and provenance-gap flags]
Rows with `has_diagram = 1` are kept (Issue 246 proposed excluding them but left it open). They
are counted separately and carry `has_diagram` in every record, so review can decide per row.

Answer-value screen: each candidate's `answer_value` is classified with the same buckets as the
integrity check's CHECK 3b. Rows whose `answer_value` looks like raw OCR'd working rather than a
final answer (`400-168=232cm2`, multi-line step dumps and so on) are excluded by default. The gate
would mostly cap them at Tier 1 anyway, and a hint grounded in a garbled answer key has little
value. Their ids are printed and written to a `*.skipped_suspect_answers.json` sidecar.
`--include-suspect-answers` keeps them.

Answer-value normalisation (`normalize_answer_value()`) applies only to the gate call in this
script; it changes neither `gate.py` nor `psle.db`. It was added because, at the time:
  `gate._values_equal('36', '$36')`  -> False  (a leading '$' was not covered by
      `gate._UNIT_SUFFIX_RE`, which only strips a trailing unit suffix)
  `gate._values_equal('64', '64°')`  -> False  ('°' was not in `_UNIT_SUFFIX_RE`)
In the 1,205-row pool, 141 rows had a leading '$', 145 a trailing '°' and 11 a Unicode '²' or '³'
(`cm²` did not match the ASCII `cm2`). Together, about 25% of the pool would have failed to match
even a correct model answer and been capped at Tier 1 for reasons unrelated to the model.
Issue 293 has since fixed these gaps in `gate.strip_units()` itself. `normalize_answer_value()` is
still kept separate on purpose:
  (1) `gate.strip_units()` also strips plain unit suffixes (`cm`, `kg`, `%`, `min`, ...) that this
      function never touched. That is harmless for the gate, which re-strips its input anyway,
      but delegating would change what this script reports as "normalised" beyond the three
      shapes measured and published (287 of 1,205 in Issue 292).
  (2) `gate.strip_units()` has no multi-line guard (it does not need one, since
      `run_full_gate_pipeline()` rejects non-numeric compound content on other grounds). The
      explicit multi-line bail-out here keeps the published count reproducible.
For the three shapes both cover, the gate outcomes are numerically equivalent, so the duplication
is for stable reporting, not a correctness gap.

Normalisation produces an `answer_value_gate` string used only in the `run_full_gate_pipeline()`
call (the comparison, and the numeric-parse check in `classify_question_type()`). The original
`answer_value` is still recorded in every row. Only single-line, single-value answers are
normalised; multi-line and compound (`"(a) ... (b) ..."`) answers are left untouched.
`--disable-normalization` uses the raw `answer_value`, for an A/B check.

Per-row timeout (`--row-timeout-seconds`, default 600). During a full-pool run, id=23 appeared to
hang for over 30 minutes. That turned out to be a monitoring artefact (it took 15.4 s; the first
71 rows took 8.5-48.1 s), but the concern stands: nothing stopped a pathological row, such as a
degenerate generation on a truncated question (id=23 is truncated, see Issue 291), from using an
unbounded share of a run of about 9 hours unnoticed. Every `generate()` and `generate_multiple()`
call has a `max_new_tokens` cap, but a slow worst case (thermal throttling, a long prompt, several
chained calls near their caps) can still take minutes. Without a ceiling, "slow but fine" cannot
be told apart from "stuck" without watching `nvidia-smi` by hand, which does not work for a long
unattended run.

The timeout is a `ThreadPoolExecutor(max_workers=1)` watchdog around each row's
`run_full_gate_pipeline()` call and the forced Tier 1 `generate_hint()` call. A timeout stops the
run rather than skipping the row. Python cannot kill a thread blocked in a C extension or CUDA
call, so the timed-out call keeps running. If the loop moved on, the next row's `generate()` would
run concurrently on the same module-level `_model` and `_tokenizer` in `llm_service.py`, and
`model.generate()` is not documented as safe for two threads sharing one instance; that risks a
CUDA error or corrupted output for both calls. So on a timeout: rows already written are safe
(each row is flushed as it is written), the timed-out row is logged to a `*.timeouts.json`
sidecar, and the process exits non-zero. Re-running with the same `--out` skips every completed
`(question_id, tier)` and retries the row that timed out.

Hint generation, per surviving candidate:
  * `gate.run_full_gate_pipeline(question_text, answer_value_gate, has_diagram,
    worked_solution_text)`, the live pipeline (self-consistency or SymPy, then method alignment,
    then the hint). One queue row is written for the hint it produces (Tier 1 if the gate capped
    it, Tier 2 if the gate passed).
  * If that hint is Tier 2 or higher, a forced Tier 1 restatement row is also written, so the
    queue covers both system-prompt shapes (Issue 246). A grounded Tier 2 hint is never written
    for a row the gate did not pass, since that is the ungrounded training pair Issues 246 and 47
    warn about.

Diagram rows: a Tier 2 or 3 hint for a `has_diagram=1` row can refer to figure content a text-only
model never saw, which a reviewer reading only the hint text cannot catch. Every row with
`has_diagram=1` and `tier >= 2` therefore carries `source_page_image` (the repository-relative
path of the cached page PNG, `data/extracted/pages/{pdf_stem}/{source_page_index}.png`) and
`source_page_image_exists` (checked on disk). Tier 1 rows and `has_diagram=0` rows never carry it,
since a Tier 1 restatement never refers to solution or figure content.

Output: JSONL, one queue row per line, under `data/extracted/slice6_step0c/` (not published):
  {"question_id", "tier", "system_prompt", "question_text", "bootstrapped_hint",
   "reviewed": false, "reviewed_hint": null, "review_notes": null,
   provenance: "gate_passed", "gate_tier_allowed", "gate_reason", "question_type",
       "grounded_in", "self_consistency_summary", "answer_value", "answer_value_gate",
       "answer_value_normalization_rules", "worked_solution_text", "has_diagram", "source_paper",
       "answer_value_class", "bootstrap_generated_at",
   plus "source_page_image" and "source_page_image_exists" (diagram rows of Tier 2+ only)}

Resumable: re-running with the same `--out` skips any (question_id, tier) already present.
Re-running on a complete file writes 0 new rows.

GPU checks (Issue 248): prints `nvidia-smi` output before loading anything, and refuses to start
if less than 3,500 MiB is free (Phi-4-mini in NF4 needs about 3 GB) or if another large ML process
looks resident. Only one large model runs at a time; this loads only Phi-4-mini, through the usual
lazy `llm_service.get_llm()` path. `--gpu-check-every N` (default 50) re-prints free VRAM every N
questions, so a leaking process is caught mid-run, and the run stops if free VRAM falls below
1,000 MiB.

Usage:
    # Small trial slice first; do not scale up without sign-off:
    backend/.venv/Scripts/python.exe scripts/training/build_hint_review_queue.py --limit 25
    # Diagram-free rows only:
    backend/.venv/Scripts/python.exe scripts/training/build_hint_review_queue.py --limit 25 \
        --diagram-free-only
    # Specific ids:
    backend/.venv/Scripts/python.exe scripts/training/build_hint_review_queue.py --ids 1455,1602,2931
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FutureTimeoutError
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO_ROOT / "backend"))

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

from sqlalchemy import text  # noqa: E402

from app.db.session import get_session, init_db  # noqa: E402

_OUT_DIR = _REPO_ROOT / "data" / "extracted" / "slice6_step0c"

# The structural candidate filter, steps 1..5 above, as one WHERE clause.
_CANDIDATE_WHERE = (
    "superseded_by IS NULL "
    "AND (extraction_flag IS NULL OR extraction_flag NOT LIKE '%non_question_boilerplate%') "
    "AND worked_solution_text IS NOT NULL AND TRIM(worked_solution_text) <> '' "
    "AND answer_value IS NOT NULL AND TRIM(answer_value) <> '' "
    "AND (extraction_flag IS NULL OR (extraction_flag NOT LIKE '%answer_key_verification_pending%' "
    "     AND extraction_flag NOT LIKE '%no_matching_answer_key_row%'))"
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def classify_answer_value(v: str) -> tuple[str, bool]:
    """Return (bucket, looks_like_raw_working), using the CHECK 3b buckets."""
    v = (v or "").strip()
    low = v.lower()

    suspect = False
    # Raw-working signals (not triggered by the clean "(a) X (b) Y" multi-part convention):
    #   - an arithmetic step that resolves with '=' ("400-168=232cm2", "6 - 5 = 1")
    #   - a step arrow
    #   - 3+ interior newlines (a multi-line step dump)
    #   - very long
    #   - an embedded "Ans:" that still has content trailing it
    if re.search(r"\d\s*[-+x×*/÷]\s*\d[^\n]*=", v):
        suspect = True
    if "→" in v:
        suspect = True
    if v.strip().count("\n") >= 3:
        suspect = True
    if re.search(r"\b(ans|answer)\s*[:=]\s*\S", low) and len(v) > 20:
        suspect = True
    if len(v) > 70:
        suspect = True

    if re.fullmatch(r"-?\d+", v):
        bucket = "plain_integer"
    elif re.fullmatch(r"-?\d*\.\d+", v):
        bucket = "plain_decimal"
    elif re.fullmatch(r"[A-Ea-e]", v):
        bucket = "single_letter"
    elif re.fullmatch(r"\(?[1-4]\)?", v):
        bucket = "paren_digit_mcq"
    elif re.fullmatch(r"\d+\s*/\s*\d+", v) or re.fullmatch(r"\d+\s+\d+/\d+", v):
        bucket = "fraction"
    elif v.startswith("$"):
        bucket = "money"
    elif re.fullmatch(r"[\d\s]+:[\d\s:]+", v):
        bucket = "ratio"
    elif re.fullmatch(r"-?[\d., ]+\s*(cm2|cm²|cm3|m2|m3|cm|mm|km|kg|g|ml|l|h|min|s|%|°|litres?)\.?",
                      low):
        bucket = "number_with_unit"
    elif ("(a)" in low and "(b)" in low) or re.match(r"^\(?[ab][\).]", low):
        bucket = "compound_ab"
    else:
        bucket = "other"

    return bucket, suspect


_TRAILING_DEGREE_RE = re.compile(r"\s*°\s*$")


def normalize_answer_value(av: str) -> tuple[str, list[str]]:
    """Normalise `answer_value` for the gate call in this script only.

    See "Answer-value normalisation" in the module docstring for the gaps this covered. Returns
    (normalized_value, rules_applied). Multi-line and already clean values are returned
    unchanged with [], so a compound answer is never partly changed.
    """
    if "\n" in av:
        return av, []
    v = av.strip()
    rules: list[str] = []
    if v.count("$") == 1 and v.startswith("$"):
        v = v[1:].strip()
        rules.append("stripped_leading_dollar")
    m = _TRAILING_DEGREE_RE.search(v)
    if m:
        v = v[: m.start()].strip()
        rules.append("stripped_trailing_degree")
    if "²" in v or "³" in v:
        v = v.replace("²", "2").replace("³", "3")
        rules.append("ascii_superscript")
    return v, rules


def report_normalization(cands: list[dict]) -> None:
    print(f"\n=== NORMALIZATION PASS (report only, full selected pool: {len(cands)} rows) ===")
    counts: dict[str, int] = {}
    touched = 0
    for r in cands:
        _, rules = normalize_answer_value(r["answer_value"])
        if rules:
            touched += 1
        for rule in rules:
            counts[rule] = counts.get(rule, 0) + 1
    print(f"  rows with >=1 normalization rule applied: {touched} / {len(cands)}")
    for k, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        print(f"    {k:<28} {n}")
    print("  before/after example:")
    shown = 0
    for r in cands:
        norm, rules = normalize_answer_value(r["answer_value"])
        if rules and shown < 6:
            print(f"    id={r['id']:<5} {r['answer_value']!r} -> {norm!r}  [{', '.join(rules)}]")
            shown += 1


def resolve_page_image(source_paper: str, page_index: int) -> tuple[str, bool]:
    """Return the repository-relative path of a row's cached page PNG and whether it exists.

    Existence is checked on disk rather than assumed from the naming pattern.
    """
    stem = Path(source_paper.replace("\\", "/")).stem
    rel = f"data/extracted/pages/{stem}/{page_index}.png"
    exists = (_REPO_ROOT / rel).exists()
    return rel, exists


def _nvidia_smi() -> tuple[str, int | None]:
    try:
        full = subprocess.run(["nvidia-smi"], capture_output=True, text=True, timeout=20).stdout
        q = subprocess.run(
            ["nvidia-smi", "--query-gpu=memory.free", "--format=csv,noheader,nounits"],
            capture_output=True, text=True, timeout=20,
        ).stdout.strip()
        free_mib = int(q.splitlines()[0].strip())
    except Exception as e:  # noqa: BLE001
        return f"(nvidia-smi unavailable: {e})", None
    return full, free_mib


def select_candidates(limit: int | None, ids: list[int] | None, diagram_free_only: bool):
    where = _CANDIDATE_WHERE
    if diagram_free_only:
        where += " AND has_diagram = 0"
    init_db()
    with get_session() as s:
        rows = s.execute(text(
            f"SELECT id, question_text, answer_value, has_diagram, worked_solution_text, "
            f"source_paper, source_page_index FROM questions WHERE {where} ORDER BY id"
        )).all()
    out = [dict(r._mapping) for r in rows]
    if ids:
        wanted = set(ids)
        out = [r for r in out if r["id"] in wanted]
    if limit is not None:
        out = out[:limit]
    return out


def report_filter_chain(diagram_free_only: bool) -> None:
    init_db()
    with get_session() as s:
        def c(w: str) -> int:
            return s.execute(text(f"SELECT COUNT(*) c FROM questions WHERE {w}")).first().c

        w1 = "superseded_by IS NULL"
        w2 = w1 + " AND (extraction_flag IS NULL OR extraction_flag NOT LIKE '%non_question_boilerplate%')"
        w3 = w2 + " AND worked_solution_text IS NOT NULL AND TRIM(worked_solution_text) <> ''"
        w4 = w3 + " AND answer_value IS NOT NULL AND TRIM(answer_value) <> ''"
        w5 = _CANDIDATE_WHERE
        print("=== PART 1 — candidate pool filter chain (fresh against psle.db) ===")
        print(f"  step 0  all rows                                     : {c('1=1')}")
        print(f"  step 1  - superseded_by IS NOT NULL                  : {c(w1)}   (-{c('1=1') - c(w1)})")
        print(f"  step 2  - non_question_boilerplate                   : {c(w2)}   (-{c(w1) - c(w2)})")
        print(f"  step 3  require worked_solution_text                 : {c(w3)}   (-{c(w2) - c(w3)})")
        print(f"  step 4  require answer_value            [NEW]        : {c(w4)}   (-{c(w3) - c(w4)})")
        print(f"  step 5  - answer_key_verification_pending / "
              f"no_matching_answer_key_row  [NEW]                     : {c(w5)}   (-{c(w4) - c(w5)})")
        print(f"\n  FINAL candidate pool                                : {c(w5)}")
        print(f"    has_diagram = 1  (kept; open design question)      : {c(w5 + ' AND has_diagram = 1')}")
        print(f"    has_diagram = 0                                    : {c(w5 + ' AND has_diagram = 0')}")
        if diagram_free_only:
            print(f"\n  --diagram-free-only in effect -> working pool       : {c(w5 + ' AND has_diagram = 0')}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--limit", type=int, default=None, help="cap the candidate slice (omit = whole pool — do NOT run without sign-off)")
    ap.add_argument("--ids", type=str, default=None, help="comma-separated question ids (overrides --limit ordering)")
    ap.add_argument("--diagram-free-only", action="store_true", help="restrict to has_diagram = 0 (Issue 246's proposed filter)")
    ap.add_argument("--include-suspect-answers", action="store_true", help="also bootstrap rows whose answer_value looks like raw working")
    ap.add_argument("--out", type=str, default=None, help="output JSONL path (default: timestamped under data/extracted/slice6_step0c/)")
    ap.add_argument("--report-only", action="store_true", help="print the filter chain + answer_value screen and exit; no model load")
    ap.add_argument("--disable-normalization", action="store_true", help="use the raw answer_value for the gate call (A/B control)")
    ap.add_argument("--gpu-check-every", type=int, default=50, help="re-print free VRAM every N questions during a long run")
    ap.add_argument("--row-timeout-seconds", type=int, default=600, help="hard ceiling per row (gate pipeline + forced-Tier-1 call combined); on timeout, progress so far is saved and the run stops (see module docstring for why this is fatal, not skip-and-continue)")
    args = ap.parse_args()

    ids = [int(x) for x in args.ids.split(",")] if args.ids else None

    report_filter_chain(args.diagram_free_only)

    cands_full_pool = select_candidates(None, None, args.diagram_free_only)
    report_normalization(cands_full_pool)

    cands = select_candidates(args.limit, ids, args.diagram_free_only)
    print(f"\n=== PART 2 — answer_value screen over the selected {len(cands)} candidate(s) ===")
    buckets: dict[str, int] = {}
    suspect_rows = []
    for r in cands:
        b, sus = classify_answer_value(r["answer_value"])
        r["_bucket"], r["_suspect"] = b, sus
        buckets[b] = buckets.get(b, 0) + 1
        if sus:
            suspect_rows.append(r)
    for k, n in sorted(buckets.items(), key=lambda kv: -kv[1]):
        print(f"  {k:<18} {n}")
    print(f"\n  answer_value looks like RAW WORKING (not a final answer): {len(suspect_rows)} / {len(cands)}")
    for r in suspect_rows:
        av = r["answer_value"].replace("\n", " / ")[:70]
        print(f"    id={r['id']:<5} diag={r['has_diagram']}  {av!r}")

    if not args.include_suspect_answers:
        skip_ids = {r["id"] for r in suspect_rows}
        cands = [r for r in cands if r["id"] not in skip_ids]
        print(f"\n  -> {len(skip_ids)} suspect-answer row(s) EXCLUDED from bootstrapping "
              f"(--include-suspect-answers to keep). {len(cands)} candidate(s) remain.")

    if args.report_only:
        print("\n--report-only: stopping before any model load.")
        return

    _OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = Path(args.out) if args.out else (
        _OUT_DIR / f"hint_review_queue_{datetime.now().strftime('%Y%m%d_%H%M%S')}.jsonl"
    )

    done: set[tuple[int, int]] = set()
    if out_path.exists():
        for line in out_path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                d = json.loads(line)
                done.add((d["question_id"], d["tier"]))
        print(f"\nResuming: {len(done)} (question_id, tier) row(s) already in {out_path.name}")

    smi, free_mib = _nvidia_smi()
    print("\n=== PART 3 — GPU state before load (nvidia-smi) ===")
    print(smi)
    if free_mib is not None:
        print(f"  parsed free VRAM: {free_mib} MiB")
        if free_mib < 3500:
            print("*** REFUSING: < 3500 MiB free — Phi-4-mini NF4 needs ~3 GB. Free the GPU and retry. ***")
            sys.exit(1)
    if smi.count("python") > 0 or "run_batched" in smi or "mineru" in smi.lower():
        print("*** REFUSING: another python/OCR ML process looks resident — one big model at a time (Section 2). ***")
        sys.exit(1)

    # Imports that load torch and transformers are deferred until after the GPU checks.
    from app.pipeline.gate import (  # noqa: E402
        _GROUNDED_HINT_PROMPT_TEMPLATE, _TIER1_SYSTEM_PROMPT, GateResult, generate_hint,
        run_full_gate_pipeline,
    )

    forced_tier1_gr = GateResult(passed=False, tier_allowed=1,
                                 reason="forced Tier 1 for training-coverage (bootstrap)", detail={})

    def emit(fh, rec: dict) -> None:
        fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
        fh.flush()

    row_timeout = args.row_timeout_seconds
    watchdog = ThreadPoolExecutor(max_workers=1)

    def _timeout_bailout(qid: int, stage: str, elapsed: float) -> None:
        """Log the timed-out row and stop the run.

        See "Per-row timeout" in the module docstring: a stuck generation thread cannot be
        killed, and running the next row's call concurrently on the same model risks corrupting
        both.
        """
        timeout_path = out_path.with_name(out_path.name + ".timeouts.json")
        existing = []
        if timeout_path.exists():
            try:
                existing = json.loads(timeout_path.read_text(encoding="utf-8"))
            except Exception:
                existing = []
        existing.append({
            "question_id": qid, "stage": stage, "timeout_seconds": row_timeout,
            "elapsed_before_bailout_s": round(elapsed, 1), "at": _now_iso(),
        })
        timeout_path.write_text(json.dumps(existing, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"\n*** ROW TIMEOUT: id={qid} ({stage}) exceeded {row_timeout}s — stopping the run. ***")
        print(f"    Progress already written is safe (every row before this one). Re-run with the "
              f"same --out to resume: it skips every completed (question_id, tier) and retries "
              f"id={qid}. Not treated as skip-and-continue on purpose — see the module docstring.")
        print(f"    Timeout logged -> {timeout_path}")
        sys.exit(2)

    tier_counts = {1: 0, 2: 0}
    norm_touched = 0
    t0 = time.time()
    with out_path.open("a", encoding="utf-8") as fh:
        for i, r in enumerate(cands, 1):
            qid, qt, av = r["id"], r["question_text"], r["answer_value"]
            wst, diag = r["worked_solution_text"], bool(r["has_diagram"])

            if args.disable_normalization:
                gate_av, norm_rules = av, []
            else:
                gate_av, norm_rules = normalize_answer_value(av)
            if norm_rules:
                norm_touched += 1

            base_prov = {
                "answer_value": av, "answer_value_gate": gate_av,
                "answer_value_normalization_rules": norm_rules,
                "worked_solution_text": wst, "has_diagram": diag,
                "source_paper": r["source_paper"], "answer_value_class": r["_bucket"],
                "bootstrap_generated_at": _now_iso(),
            }

            def _diagram_fields(tier: int) -> dict:
                if diag and tier >= 2:
                    img, exists = resolve_page_image(r["source_paper"], r["source_page_index"])
                    return {"source_page_image": img, "source_page_image_exists": exists}
                return {}

            q_start = time.time()
            fut = watchdog.submit(run_full_gate_pipeline, qt, gate_av,
                                   has_diagram=diag, worked_solution_text=wst)
            try:
                gr, hint, sc_summary = fut.result(timeout=row_timeout)
            except FutureTimeoutError:
                _timeout_bailout(qid, "run_full_gate_pipeline", time.time() - q_start)
            nat_tier = int(hint["tier"])

            if (qid, nat_tier) not in done:
                sysp = _TIER1_SYSTEM_PROMPT if nat_tier == 1 else _GROUNDED_HINT_PROMPT_TEMPLATE.format(
                    verified_content=wst)
                emit(fh, {
                    "question_id": qid, "tier": nat_tier, "system_prompt": sysp,
                    "question_text": qt, "bootstrapped_hint": hint["hint_text"],
                    "reviewed": False, "reviewed_hint": None, "review_notes": None,
                    "gate_passed": bool(gr.passed), "gate_tier_allowed": int(gr.tier_allowed),
                    "gate_reason": gr.reason, "question_type": gr.detail.get("question_type")
                    or ("sum" if "expr_str" in gr.detail else "reasoning"),
                    "grounded_in": hint.get("grounded_in"),
                    "self_consistency_summary": sc_summary, **base_prov,
                    **_diagram_fields(nat_tier),
                })
                tier_counts[nat_tier] = tier_counts.get(nat_tier, 0) + 1
                done.add((qid, nat_tier))

            # Forced Tier 1 coverage row when the natural hint was grounded (Tier 2 or higher).
            if nat_tier >= 2 and (qid, 1) not in done:
                t1_start = time.time()
                fut1 = watchdog.submit(generate_hint, qt, forced_tier1_gr)
                try:
                    t1 = fut1.result(timeout=row_timeout)
                except FutureTimeoutError:
                    _timeout_bailout(qid, "generate_hint (forced Tier 1)", time.time() - t1_start)
                emit(fh, {
                    "question_id": qid, "tier": 1, "system_prompt": _TIER1_SYSTEM_PROMPT,
                    "question_text": qt, "bootstrapped_hint": t1["hint_text"],
                    "reviewed": False, "reviewed_hint": None, "review_notes": None,
                    "gate_passed": bool(gr.passed), "gate_tier_allowed": int(gr.tier_allowed),
                    "gate_reason": "forced Tier-1 restate for training coverage (gate result: "
                                   + gr.reason + ")",
                    "question_type": ("sum" if "expr_str" in gr.detail else "reasoning"),
                    "grounded_in": None, "self_consistency_summary": sc_summary, **base_prov,
                    # Tier 1 never carries source_page_image, see module docstring.
                })
                tier_counts[1] = tier_counts.get(1, 0) + 1
                done.add((qid, 1))

            elapsed = time.time() - t0
            norm_tag = f" norm={norm_rules}" if norm_rules else ""
            print(f"  [{i}/{len(cands)}] id={qid} natural_tier={nat_tier} "
                  f"gate_passed={gr.passed} ({time.time() - q_start:.1f}s, total {elapsed:.0f}s)"
                  f"{norm_tag} | queue tiers so far: T1={tier_counts.get(1,0)} T2={tier_counts.get(2,0)}")

            if args.gpu_check_every and i % args.gpu_check_every == 0:
                _, free_mib_now = _nvidia_smi()
                print(f"      [GPU check @ {i}] free VRAM: {free_mib_now} MiB")
                if free_mib_now is not None and free_mib_now < 1000:
                    print("      *** VRAM critically low mid-run — stopping before the next question. ***")
                    break

    print(f"\n  normalization applied this run: {norm_touched} / {len(cands)} row(s)")

    smi_after, free_after = _nvidia_smi()
    print("\n=== GPU state AFTER the run (nvidia-smi) ===")
    print(smi_after)
    if free_after is not None:
        print(f"  parsed free VRAM: {free_after} MiB")

    diag_img_rows = []
    for line in out_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        d = json.loads(line)
        if "source_page_image" in d:
            diag_img_rows.append(d)
    print(f"\n  Tier>=2 diagram rows carrying source_page_image: {len(diag_img_rows)}")
    missing = [d for d in diag_img_rows if not d["source_page_image_exists"]]
    print(f"    of which the image file is MISSING on disk: {len(missing)}")
    for d in missing[:10]:
        print(f"      id={d['question_id']}: {d['source_page_image']!r}")

    print(f"\nDONE. Wrote review queue -> {out_path}")
    print(f"  rows: {sum(tier_counts.values())}  (Tier 1: {tier_counts.get(1,0)}, Tier 2: {tier_counts.get(2,0)})")
    if suspect_rows and not args.include_suspect_answers:
        side = out_path.with_suffix(".skipped_suspect_answers.json")
        side.write_text(json.dumps(
            [{"id": r["id"], "answer_value": r["answer_value"], "has_diagram": r["has_diagram"]}
             for r in suspect_rows], indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"  skipped-suspect-answer ids -> {side}")
    print("\nNEXT: human review/edit every row (set reviewed=true + reviewed_hint). "
          "Do NOT scale to the full pool without sign-off.")


if __name__ == "__main__":
    main()
